# Generated by Django 6.0.3 on 2026-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Employee', max_length=100),
        ),
    ]
