# Generated by Django 6.0.3 on 2026-03-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_absence_is_paid_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Manual', 'Manual (Admin Override)'), ('Invalid', 'Invalid (Out of range)')], max_length=20),
        ),
    ]
