# Generated by Django 6.0.3 on 2026-03-14 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration between IN and OUT in minutes', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
