# Generated by Django 6.0.3 on 2026-03-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendance_is_late_attendance_work_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='emp_id_prefix',
            field=models.CharField(default='EMP', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='next_serial',
            field=models.IntegerField(default=1),
        ),
    ]
