# Generated by Django 6.0.3 on 2026-03-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_emp_id_prefix_company_next_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='serial_padding',
            field=models.IntegerField(default=1),
        ),
    ]
