# Generated by Django 6.0.3 on 2026-03-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_serial_padding'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Planned', 'Planned/Vacation'), ('Other', 'Other')], default='Planned', max_length=20),
        ),
        migrations.AddField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
    ]
