# Generated by Django 6.0.3 on 2026-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_company_smtp_from_email_company_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
    ]
