# Generated by Django 6.0.3 on 2026-03-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_company_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
