from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('mark_attendance/', views.mark_attendance, name='mark_attendance_base'),
    path('mark_attendance/<slug:company_slug>/', views.mark_attendance, name='mark_attendance'),
    path('dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('dashboard/qr/', views.dashboard_qr, name='dashboard_qr'),
    path('dashboard/employees/', views.dashboard_employees, name='dashboard_employees'),
    path('dashboard/employees/add/', views.dashboard_add_employee, name='dashboard_add_employee'),
    path('dashboard/employees/edit/<str:emp_id>/', views.dashboard_edit_employee, name='dashboard_edit_employee'),
    path('dashboard/employees/delete/<str:emp_id>/', views.dashboard_delete_employee, name='dashboard_delete_employee'),
    path('dashboard/settings/', views.dashboard_settings, name='dashboard_settings'),
    path('dashboard/attendance/', views.dashboard_attendance, name='dashboard_attendance'),
    path('dashboard/salary/', views.admin_dashboard, name='dashboard_salary'),
    path('dashboard/salary/print/<str:emp_id>/<str:month_str>/', views.print_salary_slip, name='print_salary_slip'),
    path('dashboard/location/', views.dashboard_location, name='dashboard_location'),
    path('dashboard/location/add/', views.dashboard_add_location, name='dashboard_add_location'),
    path('dashboard/location/edit/<int:location_id>/', views.dashboard_edit_location, name='dashboard_edit_location'),
    path('dashboard/location/delete/<int:location_id>/', views.dashboard_delete_location, name='dashboard_delete_location'),
    path('dashboard/mark_absence/', views.dashboard_mark_absence, name='dashboard_mark_absence'),
    path('dashboard/leaves/', views.dashboard_leaves, name='dashboard_leaves'),
    path('dashboard/leaves/approve/<int:absence_id>/', views.dashboard_approve_leave, name='dashboard_approve_leave'),
    path('dashboard/leaves/reject/<int:absence_id>/', views.dashboard_reject_leave, name='dashboard_reject_leave'),
    path('dashboard/mark_present/', views.dashboard_mark_present, name='dashboard_mark_present'),

    path('dashboard/map/', views.dashboard_map, name='dashboard_map'),
    path('dashboard/assets/', views.dashboard_assets, name='dashboard_assets'),
    path('dashboard/hr-documents/', views.dashboard_hr_documents, name='dashboard_hr_documents'),
    path('dashboard/financial-requests/', views.dashboard_financial_requests, name='dashboard_financial_requests'),
    path('dashboard/finance/update/<str:req_type>/<int:req_id>/<str:action>/', views.dashboard_update_finance, name='dashboard_update_finance'),
    
    path('portal/', views.employee_portal, name='employee_portal'),
    path('portal/leaves/', views.employee_portal_leaves, name='employee_portal_leaves'),
    path('portal/documents/', views.employee_portal_documents, name='employee_portal_documents'),
    path('portal/payroll-requests/', views.employee_portal_payroll, name='employee_portal_payroll'),
    path('portal/profile-edit/', views.employee_profile_edit, name='employee_profile_edit'),
    path('export_attendance/', views.export_attendance, name='export_attendance'),
    path('check_punch_status/<slug:company_slug>/<str:employee_id>/', views.check_punch_status, name='check_punch_status'),
]
